site_name: rclref
nav:
  - 'Home': 'index.md'
  - 'How to setup a riak_core_lite application?': 'setup.md'
  - 'How are put, get, delete implemented in rclref?': 'put_get_delete.md'
  - 'How to test distributed Erlang application using Common Test?': 'test.md'
  - 'How to benchmark riak_core_lite application?': 'benchmark.md'
  - 'How to actually use rclref?': 'usage.md'
  - 'Other' : 'other.md'
theme: readthedocs
markdown_extensions:
  - meta
  - pymdownx.mark
  - pymdownx.magiclink
  - pymdownx.emoji
  - fontawesome_markdown
  - pymdownx.keys
  - def_list
  - admonition
  - codehilite:
      linenums: true
      use_pygments: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
          
extra_css:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js